<?php
declare(strict_types=1);

/**
 * Shared professional PDF / CSV / Excel reports.
 * Layout is a formal register — not a copy of the on-screen UI.
 */

function report_plain_date(?string $d): string
{
    if ($d === null || $d === '') {
        return '';
    }
    $ts = strtotime($d);
    return $ts ? date('d-m-Y', $ts) : $d;
}

function report_plain_amount($n): string
{
    if ($n === null || $n === '') {
        return '';
    }
    return number_format((float) $n, 2, '.', '');
}

function report_display_period(?string $from, ?string $to, string $month = '', string $year = ''): string
{
    if ($month !== '') {
        return date('F Y', strtotime($month . '-01'));
    }
    if ($year !== '') {
        return 'Year ' . $year;
    }
    $a = report_plain_date($from);
    $b = report_plain_date($to);
    if ($a !== '' && $b !== '') {
        return $a . ' to ' . $b;
    }
    if ($a !== '') {
        return 'From ' . $a;
    }
    if ($b !== '') {
        return 'Upto ' . $b;
    }
    return 'All time';
}

function report_export_buttons(array $hidden = []): string
{
    $html = '<form method="post" class="no-print" style="display:inline-flex;gap:0.35rem;flex-wrap:wrap;align-items:center">';
    $html .= csrf_field();
    foreach ($hidden as $name => $value) {
        if ($value === null || $value === '') {
            continue;
        }
        $html .= '<input type="hidden" name="' . e((string) $name) . '" value="' . e((string) $value) . '">';
    }
    $html .= '<button class="btn btn-outline" type="submit" name="export_action" value="pdf">PDF</button>';
    $html .= '<button class="btn btn-outline" type="submit" name="export_action" value="excel">Excel</button>';
    $html .= '<button class="btn btn-outline" type="submit" name="export_action" value="csv">CSV</button>';
    $html .= '</form>';
    return $html;
}

/**
 * @param array{
 *   filename: string,
 *   title: string,
 *   orientation?: string,
 *   meta?: list<array{0:string,1:string}>,
 *   summary?: list<array{0:string,1:mixed,2?:string}>,
 *   tables?: list<array{title:string,columns:list<array{label:string,type?:string,width?:string}>,rows:list<list<mixed>>,totals?:?list<mixed>}>,
 *   notes?: list<string>
 * } $report
 */
function report_download(string $format, array $report): void
{
    $format = strtolower($format);
    $stamp = date('Ymd_His');
    $base = preg_replace('/[^\w.\-]+/', '_', $report['filename'] ?? 'report') ?: 'report';
    $report['generated_at'] = date('d-m-Y h:i A');
    $report['generated_by'] = (string) (current_user()['name'] ?? '');

    if ($format === 'csv') {
        report_csv_stream($base . '_' . $stamp . '.csv', $report);
        return;
    }
    if ($format === 'excel') {
        report_excel_stream($base . '_' . $stamp . '.xls', $report);
        return;
    }
    if ($format === 'pdf') {
        report_pdf_stream($base . '_' . $stamp . '.pdf', $report);
        return;
    }
    flash('error', 'Unknown export format.');
}

function report_csv_stream(string $filename, array $report): void
{
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Pragma: no-cache');
    header('Expires: 0');
    $out = fopen('php://output', 'w');
    fwrite($out, "\xEF\xBB\xBF");

    fputcsv($out, ['SAI KUBER DEVELOPERS']);
    fputcsv($out, [$report['title'] ?? 'REPORT']);
    fputcsv($out, ['Report generated', $report['generated_at'] ?? '']);
    fputcsv($out, ['Generated by', $report['generated_by'] ?? '']);
    fputcsv($out, []);

    if (!empty($report['meta'])) {
        fputcsv($out, ['FILTERS / PARTICULARS']);
        fputcsv($out, ['Field', 'Value']);
        foreach ($report['meta'] as $row) {
            fputcsv($out, [$row[0] ?? '', $row[1] ?? '']);
        }
        fputcsv($out, []);
    }

    if (!empty($report['summary'])) {
        fputcsv($out, ['SUMMARY']);
        fputcsv($out, ['Metric', 'Value']);
        foreach ($report['summary'] as $row) {
            $type = $row[2] ?? 'text';
            $val = $row[1] ?? '';
            if ($type === 'money') {
                $val = report_plain_amount($val);
            }
            fputcsv($out, [$row[0] ?? '', $val]);
        }
        fputcsv($out, []);
    }

    foreach ($report['tables'] ?? [] as $table) {
        fputcsv($out, [strtoupper((string) ($table['title'] ?? 'DATA'))]);
        $labels = array_map(fn($c) => $c['label'] ?? '', $table['columns'] ?? []);
        fputcsv($out, $labels);
        foreach ($table['rows'] ?? [] as $row) {
            fputcsv($out, report_csv_row($row, $table['columns'] ?? []));
        }
        if (!empty($table['totals'])) {
            fputcsv($out, report_csv_row($table['totals'], $table['columns'] ?? []));
        }
        fputcsv($out, []);
    }

    foreach ($report['notes'] ?? ['All amounts are in Indian Rupees (INR).', 'Confidential — internal use only.'] as $note) {
        fputcsv($out, [$note]);
    }
    fclose($out);
    exit;
}

function report_csv_row(array $row, array $columns): array
{
    $out = [];
    foreach ($columns as $i => $col) {
        $val = $row[$i] ?? '';
        $type = $col['type'] ?? 'text';
        if ($type === 'money') {
            $out[] = ($val === null || $val === '') ? '' : report_plain_amount($val);
        } else {
            $out[] = $val === null ? '' : (string) $val;
        }
    }
    return $out;
}

function report_xls_esc($v): string
{
    $v = (string) $v;
    $v = preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F]/', '', $v) ?? $v;
    if (function_exists('mb_check_encoding') && !mb_check_encoding($v, 'UTF-8')) {
        $v = mb_convert_encoding($v, 'UTF-8', 'UTF-8');
    }
    return htmlspecialchars($v, ENT_XML1 | ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

/** Excel worksheet names: 31 chars, unique, no special punctuation. */
function report_xls_sheet_name(string $title, array &$used, int $sheetNo): string
{
    $name = substr(preg_replace('/[^\w ]+/', '', $title) ?: 'Data', 0, 28);
    $name = trim($name) !== '' ? $name : ('Sheet' . $sheetNo);
    $base = $name;
    $i = 2;
    while (isset($used[strtolower($name)])) {
        $suffix = ' ' . $i;
        $name = substr($base, 0, max(1, 31 - strlen($suffix))) . $suffix;
        $i++;
    }
    $used[strtolower($name)] = true;
    return $name;
}

function report_xls_cell($value, string $type = 'String', string $style = ''): string
{
    $styleAttr = $style !== '' ? ' ss:StyleID="' . $style . '"' : '';
    if ($type === 'Number') {
        if ($value === null || $value === '') {
            return '<Cell' . $styleAttr . '/>';
        }
        return '<Cell' . $styleAttr . '><Data ss:Type="Number">' . report_xls_esc(report_plain_amount($value)) . '</Data></Cell>';
    }
    if ($type === 'Int') {
        if ($value === null || $value === '') {
            return '<Cell' . $styleAttr . '/>';
        }
        return '<Cell' . $styleAttr . '><Data ss:Type="Number">' . report_xls_esc((string) (int) $value) . '</Data></Cell>';
    }
    return '<Cell' . $styleAttr . '><Data ss:Type="String">' . report_xls_esc((string) $value) . '</Data></Cell>';
}

function report_excel_write_heading(array $report): void
{
    echo '<Row>' . report_xls_cell('SAI KUBER DEVELOPERS', 'String', 'Brand') . '</Row>';
    echo '<Row>' . report_xls_cell($report['title'] ?? 'REPORT', 'String', 'DocTitle') . '</Row>';
    echo '<Row>' . report_xls_cell('Report generated', 'String', 'Label') . report_xls_cell($report['generated_at'] ?? '') . '</Row>';
    echo '<Row>' . report_xls_cell('Generated by', 'String', 'Label') . report_xls_cell($report['generated_by'] ?? '') . '</Row>';
    echo '<Row>' . report_xls_cell('') . '</Row>';
    if (!empty($report['meta'])) {
        echo '<Row>' . report_xls_cell('FILTERS / PARTICULARS', 'String', 'Section') . '</Row>';
        echo '<Row>' . report_xls_cell('Field', 'String', 'Header') . report_xls_cell('Value', 'String', 'Header') . '</Row>';
        foreach ($report['meta'] as $row) {
            echo '<Row>' . report_xls_cell($row[0] ?? '', 'String', 'Label') . report_xls_cell($row[1] ?? '') . '</Row>';
        }
        echo '<Row>' . report_xls_cell('') . '</Row>';
    }
    if (!empty($report['summary'])) {
        echo '<Row>' . report_xls_cell('SUMMARY', 'String', 'Section') . '</Row>';
        echo '<Row>' . report_xls_cell('Metric', 'String', 'Header') . report_xls_cell('Value', 'String', 'Header') . '</Row>';
        foreach ($report['summary'] as $row) {
            $type = $row[2] ?? 'text';
            $valCell = $type === 'money'
                ? report_xls_cell($row[1] ?? '', 'Number', 'Money')
                : ($type === 'int' ? report_xls_cell($row[1] ?? '', 'Int') : report_xls_cell($row[1] ?? ''));
            echo '<Row>' . report_xls_cell($row[0] ?? '', 'String', 'Label') . $valCell . '</Row>';
        }
        echo '<Row>' . report_xls_cell('') . '</Row>';
    }
}

function report_excel_write_table(array $table): void
{
    $columns = $table['columns'] ?? [];
    echo '<Row>' . report_xls_cell($table['title'] ?? 'DATA', 'String', 'Section') . '</Row>';
    echo '<Row>';
    foreach ($columns as $col) {
        echo report_xls_cell($col['label'] ?? '', 'String', 'Header');
    }
    echo '</Row>';
    foreach ($table['rows'] ?? [] as $row) {
        echo '<Row>' . report_excel_data_row($row, $columns, false) . '</Row>';
    }
    if (!empty($table['totals'])) {
        echo '<Row>' . report_excel_data_row($table['totals'], $columns, true) . '</Row>';
    }
    echo '<Row>' . report_xls_cell('') . '</Row>';
}

function report_excel_stream(string $filename, array $report): void
{
    while (ob_get_level() > 0) {
        ob_end_clean();
    }
    header('Content-Type: application/vnd.ms-excel; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Pragma: no-cache');
    header('Expires: 0');

    echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
    echo '<?mso-application progid="Excel.Sheet"?>' . "\n";
    echo '<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"'
        . ' xmlns:o="urn:schemas-microsoft-com:office:office"'
        . ' xmlns:x="urn:schemas-microsoft-com:office:excel"'
        . ' xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">' . "\n";
    echo '<DocumentProperties xmlns="urn:schemas-microsoft-com:office:office">'
        . '<Title>' . report_xls_esc($report['title'] ?? 'Report') . '</Title>'
        . '<Author>Sai Kuber Developers</Author>'
        . '<Created>' . date('c') . '</Created>'
        . '</DocumentProperties>' . "\n";
    echo '<Styles>'
        . '<Style ss:ID="Default" ss:Name="Normal"><Font ss:FontName="Calibri" ss:Size="11"/></Style>'
        . '<Style ss:ID="Brand"><Font ss:FontName="Calibri" ss:Size="16" ss:Bold="1" ss:Color="#0F766E"/></Style>'
        . '<Style ss:ID="DocTitle"><Font ss:FontName="Calibri" ss:Size="13" ss:Bold="1"/></Style>'
        . '<Style ss:ID="Section"><Font ss:FontName="Calibri" ss:Size="12" ss:Bold="1" ss:Color="#0F766E"/></Style>'
        . '<Style ss:ID="Label"><Font ss:Bold="1"/><Interior ss:Color="#F3FAF8" ss:Pattern="Solid"/></Style>'
        . '<Style ss:ID="Header"><Font ss:Bold="1" ss:Color="#FFFFFF" ss:Size="10"/>'
        . '<Interior ss:Color="#0F766E" ss:Pattern="Solid"/>'
        . '<Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1"/></Style>'
        . '<Style ss:ID="Money"><NumberFormat ss:Format="#,##0.00"/><Alignment ss:Horizontal="Right"/></Style>'
        . '<Style ss:ID="MoneyTotal"><Font ss:Bold="1"/><NumberFormat ss:Format="#,##0.00"/>'
        . '<Interior ss:Color="#EEF8F5" ss:Pattern="Solid"/><Alignment ss:Horizontal="Right"/></Style>'
        . '<Style ss:ID="Total"><Font ss:Bold="1"/><Interior ss:Color="#EEF8F5" ss:Pattern="Solid"/></Style>'
        . '<Style ss:ID="Muted"><Font ss:Color="#5B6F6B" ss:Size="10"/></Style>'
        . '<Style ss:ID="Text"><Alignment ss:Vertical="Center" ss:WrapText="1"/></Style>'
        . '</Styles>' . "\n";

    $tables = $report['tables'] ?? [];
    $usedNames = [];

    // First sheet has summary + every table so Excel / Sheets open with all entries visible.
    $maxCols = 3;
    $colWidths = [40, 180, 160];
    foreach ($tables as $table) {
        $cols = $table['columns'] ?? [];
        $maxCols = max($maxCols, count($cols));
        foreach ($cols as $i => $col) {
            $w = isset($col['xls_width']) ? (int) $col['xls_width'] : 90;
            if (!isset($colWidths[$i]) || $w > $colWidths[$i]) {
                $colWidths[$i] = $w;
            }
        }
    }
    $reportSheet = report_xls_sheet_name('Report', $usedNames, 1);
    echo '<Worksheet ss:Name="' . report_xls_esc($reportSheet) . '"><Table>';
    for ($i = 0; $i < $maxCols; $i++) {
        echo '<Column ss:Width="' . (int) ($colWidths[$i] ?? 90) . '"/>';
    }
    echo "\n";
    report_excel_write_heading($report);
    foreach ($tables as $table) {
        report_excel_write_table($table);
    }
    foreach ($report['notes'] ?? ['Confidential — internal use only.'] as $note) {
        echo '<Row>' . report_xls_cell($note, 'String', 'Muted') . '</Row>';
    }
    echo '</Table></Worksheet>' . "\n";

    $sheetNo = 1;
    foreach ($tables as $table) {
        $sheetNo++;
        $name = report_xls_sheet_name((string) ($table['title'] ?? 'Data'), $usedNames, $sheetNo);
        $columns = $table['columns'] ?? [];
        echo '<Worksheet ss:Name="' . report_xls_esc($name) . '"><Table>';
        foreach ($columns as $col) {
            $w = isset($col['xls_width']) ? (int) $col['xls_width'] : 90;
            echo '<Column ss:Width="' . $w . '"/>';
        }
        echo "\n";
        report_excel_write_table($table);
        echo '</Table></Worksheet>' . "\n";
    }

    echo '</Workbook>';
    exit;
}

function report_excel_data_row(array $row, array $columns, bool $isTotal): string
{
    $html = '';
    foreach ($columns as $i => $col) {
        $val = $row[$i] ?? '';
        $type = $col['type'] ?? 'text';
        if ($type === 'money') {
            $html .= report_xls_cell($val, 'Number', $isTotal ? 'MoneyTotal' : 'Money');
        } elseif ($type === 'int') {
            $html .= report_xls_cell($val, 'Int', $isTotal ? 'Total' : '');
        } else {
            $html .= report_xls_cell($val, 'String', $isTotal ? 'Total' : 'Text');
        }
    }
    return $html;
}

function report_pdf_stream(string $filename, array $report): void
{
    sk_require_pdf();
    $title = (string) ($report['title'] ?? 'REPORT');
    $orientation = $report['orientation'] ?? 'landscape';
    ob_start();
    ?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  @page { margin: 12mm 10mm; }
  * { box-sizing: border-box; }
  body { font-family: DejaVu Sans, sans-serif; font-size: 8.5pt; color: #0b1f1c; margin: 0; line-height: 1.3; }
  .brand { font-size: 14pt; font-weight: 700; color: #0f766e; margin: 0 0 2px; }
  .doc-title { font-size: 10.5pt; font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em; margin: 0 0 6px; }
  .meta { font-size: 8pt; color: #5b6f6b; }
  .header-table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
  .header-table td { vertical-align: top; padding: 0; }
  .header-table td.right { text-align: right; }
  .summary { width: 100%; border-collapse: collapse; margin: 4px 0 10px; border: 1px solid #cfe3df; }
  .summary td { padding: 7px 9px; border-right: 1px solid #cfe3df; background: #f7fcfb; vertical-align: top; }
  .summary td:last-child { border-right: none; }
  .summary .label { font-size: 6.5pt; text-transform: uppercase; letter-spacing: 0.05em; color: #5b6f6b; font-weight: 700; margin-bottom: 2px; }
  .summary .value { font-size: 10pt; font-weight: 700; }
  h3 { font-size: 9.5pt; margin: 12px 0 5px; color: #0f766e; border-bottom: 1px solid #cfe3df; padding-bottom: 3px; }
  table.data { width: 100%; border-collapse: collapse; table-layout: fixed; font-size: 7.5pt; }
  table.data th, table.data td { border: 1px solid #d7e6e2; padding: 3px 4px; vertical-align: top; }
  table.data th { background: #eef8f5; font-size: 6.5pt; text-transform: uppercase; letter-spacing: 0.03em; text-align: left; }
  table.data td.num, table.data th.num { text-align: right; white-space: nowrap; }
  table.data thead { display: table-header-group; }
  table.data tfoot { display: table-row-group; }
  table.data tr { page-break-inside: avoid; }
  table.data tfoot td { background: #eef8f5; font-weight: 700; border-top: 2px solid #9ec5bd; }
  .filters { width: 100%; border-collapse: collapse; margin-bottom: 8px; font-size: 8pt; }
  .filters td { padding: 2px 8px 2px 0; }
  .filters .k { color: #5b6f6b; width: 18%; }
  .footnote { margin-top: 12px; padding-top: 8px; border-top: 1px solid #cfe3df; font-size: 7pt; color: #5b6f6b; }
  .footnote p { margin: 2px 0; }
</style>
</head>
<body>
  <table class="header-table">
    <tr>
      <td>
        <div class="brand">Sai Kuber Developers</div>
        <div class="doc-title"><?= pdf_e($title) ?></div>
      </td>
      <td class="right meta">
        Generated <?= pdf_e($report['generated_at'] ?? '') ?><br>
        By <?= pdf_e($report['generated_by'] ?? '') ?>
      </td>
    </tr>
  </table>

  <?php if (!empty($report['meta'])): ?>
  <table class="filters">
    <?php foreach ($report['meta'] as $row): ?>
      <tr><td class="k"><?= pdf_e($row[0] ?? '') ?></td><td><?= pdf_e($row[1] ?? '') ?></td></tr>
    <?php endforeach; ?>
  </table>
  <?php endif; ?>

  <?php if (!empty($report['summary'])): ?>
  <table class="summary"><tr>
    <?php foreach ($report['summary'] as $row):
        $type = $row[2] ?? 'text';
        $val = $row[1] ?? '';
        if ($type === 'money') {
            $val = money($val);
        }
    ?>
      <td>
        <div class="label"><?= pdf_e($row[0] ?? '') ?></div>
        <div class="value"><?= pdf_e((string) $val) ?></div>
      </td>
    <?php endforeach; ?>
  </tr></table>
  <?php endif; ?>

  <?php foreach ($report['tables'] ?? [] as $table):
      $columns = $table['columns'] ?? [];
      $pdfCols = [];
      foreach ($columns as $i => $col) {
          if (($col['pdf'] ?? true) === false) {
              continue;
          }
          $pdfCols[] = ['i' => $i, 'col' => $col];
      }
  ?>
    <h3><?= pdf_e($table['title'] ?? 'Data') ?></h3>
    <table class="data">
      <thead>
        <tr>
          <?php foreach ($pdfCols as $item):
              $col = $item['col'];
              $isNum = in_array($col['type'] ?? 'text', ['money', 'int'], true);
              $w = !empty($col['width']) ? ' style="width:' . pdf_e($col['width']) . '"' : '';
          ?>
            <th class="<?= $isNum ? 'num' : '' ?>"<?= $w ?>><?= pdf_e($col['label'] ?? '') ?></th>
          <?php endforeach; ?>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($table['rows'] ?? [] as $row): ?>
          <tr>
            <?php foreach ($pdfCols as $item):
                $col = $item['col'];
                $i = $item['i'];
                $isNum = in_array($col['type'] ?? 'text', ['money', 'int'], true);
                $val = $row[$i] ?? '';
                if (($col['type'] ?? '') === 'money') {
                    $val = ($val === null || $val === '') ? '—' : indian_number_format((float) $val, 2);
                } elseif ($val === null || $val === '') {
                    $val = $isNum ? '—' : '';
                }
            ?>
              <td class="<?= $isNum ? 'num' : '' ?>"><?= pdf_e((string) $val) ?></td>
            <?php endforeach; ?>
          </tr>
        <?php endforeach; ?>
      </tbody>
      <?php if (!empty($table['totals'])): ?>
      <tfoot>
        <tr>
          <?php foreach ($pdfCols as $item):
              $col = $item['col'];
              $i = $item['i'];
              $isNum = in_array($col['type'] ?? 'text', ['money', 'int'], true);
              $val = $table['totals'][$i] ?? '';
              if (($col['type'] ?? '') === 'money' && $val !== '' && $val !== null && !is_string($val)) {
                  $val = indian_number_format((float) $val, 2);
              }
          ?>
            <td class="<?= $isNum ? 'num' : '' ?>"><?= pdf_e((string) $val) ?></td>
          <?php endforeach; ?>
        </tr>
      </tfoot>
      <?php endif; ?>
    </table>
  <?php endforeach; ?>

  <div class="footnote">
    <?php foreach ($report['notes'] ?? ['System-generated report. Figures match the selected filters at export time.', 'Confidential — internal use only.'] as $note): ?>
      <p><?= pdf_e($note) ?></p>
    <?php endforeach; ?>
  </div>
</body>
</html>
    <?php
    $html = ob_get_clean();
    try {
        pdf_download($html, $filename, $orientation, 'A4');
    } catch (Throwable $e) {
        flash('error', 'PDF generation failed: ' . $e->getMessage());
    }
}
